// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krctlzpozxtygyteeqii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyY3RsenBvenh0eWd5dGVlcWlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MjcyNzAsImV4cCI6MjA3ODIwMzI3MH0.ZzE32HjIrOBbdITEEAdza1sc8zokgtp8dvKrksrTfGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});